# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName('gridLayout_3')
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName('gridLayout')
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setObjectName('gridLayout_1')
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName('groupBox')
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName('gridLayout_4')
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setObjectName('textBrowser')
        self.gridLayout_4.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_1.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName('groupBox_2')
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser_2.setObjectName('textBrowser_2')
        self.gridLayout_2.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.gridLayout_1.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_1)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName('statusbar')
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName('menubar')
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName('menu')
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName('menu_2')
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName('menu_3')
        self.filters = QtWidgets.QMenu(self.menubar)
        self.filters.setObjectName('filters')
        self.menu_11 = QtWidgets.QMenu(self.filters)
        self.menu_11.setObjectName('menu_11')
        self.menu_12 = QtWidgets.QMenu(self.filters)
        self.menu_12.setObjectName('menu_12')
        self.menu_13 = QtWidgets.QMenu(self.filters)
        self.menu_13.setObjectName('menu_13')
        self.registration = QtWidgets.QMenu(self.menubar)
        self.registration.setObjectName('registration')
        self.menuGlobal = QtWidgets.QMenu(self.registration)
        self.menuGlobal.setObjectName('menuGlobal')
        self.menu_14 = QtWidgets.QMenu(self.registration)
        self.menu_14.setObjectName('menu_14')
        self.menuICP = QtWidgets.QMenu(self.registration)
        self.menuICP.setObjectName('menuICP')
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName('menu_6')
        self.menu_7 = QtWidgets.QMenu(self.menubar)
        self.menu_7.setObjectName('menu_7')
        self.menu_8 = QtWidgets.QMenu(self.menubar)
        self.menu_8.setObjectName('menu_8')
        self.menu_9 = QtWidgets.QMenu(self.menubar)
        self.menu_9.setObjectName('menu_9')
        self.menu_10 = QtWidgets.QMenu(self.menubar)
        self.menu_10.setObjectName('menu_10')
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName('toolBar')
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName('toolBar_2')
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar_2)
        self.actionread = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(':/Icons/Icons/ic_read.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionread.setIcon(icon)
        self.actionread.setObjectName('actionread')
        self.actionsave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(':/Icons/Icons/ic_save.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionsave.setIcon(icon1)
        self.actionsave.setObjectName('actionsave')
        self.actionquit = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(':/Icons/Icons/ic_quit.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionquit.setIcon(icon2)
        self.actionquit.setObjectName('actionquit')
        self.actionviewup = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(':/Icons/Icons/ic_up.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionviewup.setIcon(icon3)
        self.actionviewup.setObjectName('actionviewup')
        self.actionviewerdown = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(':/Icons/Icons/ic_down.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionviewerdown.setIcon(icon4)
        self.actionviewerdown.setObjectName('actionviewerdown')
        self.actionviewfront = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(':/Icons/Icons/ic_front.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionviewfront.setIcon(icon5)
        self.actionviewfront.setObjectName('actionviewfront')
        self.actionviewback = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(':/Icons/Icons/ic_back.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionviewback.setIcon(icon6)
        self.actionviewback.setObjectName('actionviewback')
        self.actionviewleft = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(':/Icons/Icons/ic_left.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionviewleft.setIcon(icon7)
        self.actionviewleft.setObjectName('actionviewleft')
        self.actionviewright = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(':/Icons/Icons/ic_right.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionviewright.setIcon(icon8)
        self.actionviewright.setObjectName('actionviewright')
        self.actionvoxel = QtWidgets.QAction(MainWindow)
        self.actionvoxel.setObjectName('actionvoxel')
        self.actionuniform = QtWidgets.QAction(MainWindow)
        self.actionuniform.setObjectName('actionuniform')
        self.actionrandom = QtWidgets.QAction(MainWindow)
        self.actionrandom.setObjectName('actionrandom')
        self.actionmiddle = QtWidgets.QAction(MainWindow)
        self.actionmiddle.setObjectName('actionmiddle')
        self.actionmean = QtWidgets.QAction(MainWindow)
        self.actionmean.setObjectName('actionmean')
        self.actionradius = QtWidgets.QAction(MainWindow)
        self.actionradius.setObjectName('actionradius')
        self.actionsor = QtWidgets.QAction(MainWindow)
        self.actionsor.setObjectName('actionsor')
        self.actionFGR = QtWidgets.QAction(MainWindow)
        self.actionFGR.setObjectName('actionFGR')
        self.actionDCP = QtWidgets.QAction(MainWindow)
        self.actionDCP.setObjectName('actionDCP')
        self.actionicp2point = QtWidgets.QAction(MainWindow)
        self.actionicp2point.setObjectName('actionicp2point')
        self.actionicp2Plane = QtWidgets.QAction(MainWindow)
        self.actionicp2Plane.setObjectName('actionicp2Plane')
        self.menu.addAction(self.actionread)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionquit)
        self.menu_11.addAction(self.actionvoxel)
        self.menu_11.addAction(self.actionuniform)
        self.menu_11.addAction(self.actionrandom)
        self.menu_12.addAction(self.actionmiddle)
        self.menu_12.addAction(self.actionmean)
        self.menu_13.addAction(self.actionradius)
        self.menu_13.addAction(self.actionsor)
        self.filters.addAction(self.menu_11.menuAction())
        self.filters.addAction(self.menu_12.menuAction())
        self.filters.addAction(self.menu_13.menuAction())
        self.menuGlobal.addAction(self.actionFGR)
        self.menu_14.addAction(self.actionDCP)
        self.menuICP.addAction(self.actionicp2point)
        self.menuICP.addAction(self.actionicp2Plane)
        self.registration.addAction(self.menuICP.menuAction())
        self.registration.addAction(self.menuGlobal.menuAction())
        self.registration.addAction(self.menu_14.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.filters.menuAction())
        self.menubar.addAction(self.registration.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())
        self.menubar.addAction(self.menu_8.menuAction())
        self.menubar.addAction(self.menu_9.menuAction())
        self.menubar.addAction(self.menu_10.menuAction())
        self.toolBar.addAction(self.actionread)
        self.toolBar.addAction(self.actionsave)
        self.toolBar.addAction(self.actionquit)
        self.toolBar_2.addAction(self.actionviewup)
        self.toolBar_2.addAction(self.actionviewerdown)
        self.toolBar_2.addAction(self.actionviewfront)
        self.toolBar_2.addAction(self.actionviewback)
        self.toolBar_2.addAction(self.actionviewleft)
        self.toolBar_2.addAction(self.actionviewright)
        self.toolBar_2.addSeparator()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', 'MainWindow'))
        self.groupBox.setTitle(_translate('MainWindow', '视图'))
        self.groupBox_2.setTitle(_translate('MainWindow', '参数'))
        self.menu.setTitle(_translate('MainWindow', '文件'))
        self.menu_2.setTitle(_translate('MainWindow', '编辑'))
        self.menu_3.setTitle(_translate('MainWindow', '关键点'))
        self.filters.setTitle(_translate('MainWindow', '滤波'))
        self.menu_11.setTitle(_translate('MainWindow', '采样'))
        self.menu_12.setTitle(_translate('MainWindow', '平滑'))
        self.menu_13.setTitle(_translate('MainWindow', '去噪'))
        self.registration.setTitle(_translate('MainWindow', '配准'))
        self.menuGlobal.setTitle(_translate('MainWindow', 'Global'))
        self.menu_14.setTitle(_translate('MainWindow', '点云网络'))
        self.menuICP.setTitle(_translate('MainWindow', 'ICP'))
        # self.menu_6.setTitle(_translate('MainWindow', '分割'))
        # self.menu_7.setTitle(_translate('MainWindow', '识别'))
        # self.menu_8.setTitle(_translate('MainWindow', '重建'))
        self.menu_9.setTitle(_translate('MainWindow', '显示'))
        self.menu_10.setTitle(_translate('MainWindow', '帮助'))
        self.toolBar.setWindowTitle(_translate('MainWindow', 'toolBar'))
        self.toolBar_2.setWindowTitle(_translate('MainWindow', 'toolBar_2'))
        self.actionread.setText(_translate('MainWindow', '读取'))
        self.actionsave.setText(_translate('MainWindow', '保存'))
        self.actionquit.setText(_translate('MainWindow', '退出'))
        self.actionviewup.setText(_translate('MainWindow', 'viewup'))
        self.actionviewerdown.setText(_translate('MainWindow', 'viewerdown'))
        self.actionviewfront.setText(_translate('MainWindow', 'viewfront'))
        self.actionviewback.setText(_translate('MainWindow', 'viewback'))
        self.actionviewleft.setText(_translate('MainWindow', 'viewleft'))
        self.actionviewright.setText(_translate('MainWindow', 'viewright'))
        self.actionvoxel.setText(_translate('MainWindow', '体素'))
        self.actionuniform.setText(_translate('MainWindow', '均匀'))
        self.actionrandom.setText(_translate('MainWindow', '随机'))
        self.actionmiddle.setText(_translate('MainWindow', '中值'))
        self.actionmean.setText(_translate('MainWindow', '均值'))
        self.actionradius.setText(_translate('MainWindow', '半径'))
        self.actionsor.setText(_translate('MainWindow', '统计'))
        self.actionFGR.setText(_translate('MainWindow', 'FGR'))
        self.actionDCP.setText(_translate('MainWindow', 'DCP'))
        self.actionicp2point.setText(_translate('MainWindow', 'icp2Point'))
        self.actionicp2Plane.setText(_translate('MainWindow', 'icp2Plane'))

import resources_rc
