# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_Dialog_fgr(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName('Dialog')
        Dialog.resize(420, 450)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName('gridLayout_2')
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName('buttonBox')
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setTitle('')
        self.groupBox.setObjectName('groupBox')
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName('gridLayout')
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName('label')
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName('lineEdit')
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName('horizontalLayout_2')
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName('label_2')
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName('lineEdit_2')
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 7)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName('horizontalLayout_3')
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName('label_3')
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName('lineEdit_3')
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 7)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName('horizontalLayout_4')
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName('label_4')
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName('lineEdit_4')
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 7)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName('horizontalLayout_7')
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName('label_7')
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_5.setObjectName('lineEdit_5')
        self.horizontalLayout_7.addWidget(self.lineEdit_5)
        self.horizontalLayout_7.setStretch(0, 3)
        self.horizontalLayout_7.setStretch(1, 7)
        self.gridLayout.addLayout(self.horizontalLayout_7, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName('horizontalLayout_5')
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName('pushButton')
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setObjectName('textBrowser')
        self.horizontalLayout_5.addWidget(self.textBrowser)
        self.horizontalLayout_5.setStretch(0, 3)
        self.horizontalLayout_5.setStretch(1, 7)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName('horizontalLayout_6')
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setObjectName('pushButton_2')
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_2.setObjectName('textBrowser_2')
        self.horizontalLayout_6.addWidget(self.textBrowser_2)
        self.horizontalLayout_6.setStretch(0, 3)
        self.horizontalLayout_6.setStretch(1, 7)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.pushButton.clicked.connect(Dialog.open_source)
        self.pushButton_2.clicked.connect(Dialog.open_target)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def open_source(self):
        print('1')
        (self.fileName1, filetype) = QFileDialog.getOpenFileName(None, '请选择点云文件:', '.', 'All Files(*);;')
        if self.fileName1 != '':
            self.textBrowser.setText(self.fileName1)

    def open_target(self):
        print('2')
        (self.fileName2, filetype) = QFileDialog.getOpenFileName(None, '请选择点云文件:', '.', 'All Files(*);;')
        if self.fileName2 != '':
            self.textBrowser_2.setText(self.fileName2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate('Dialog', 'FGR配准'))
        self.label.setText(_translate('Dialog', '法线半径:'))
        self.lineEdit.setText(_translate('Dialog', '0.5'))
        self.label_2.setText(_translate('Dialog', '法线最大近邻:'))
        self.lineEdit_2.setText(_translate('Dialog', '30'))
        self.label_3.setText(_translate('Dialog', 'FPFH搜索半径:'))
        self.lineEdit_3.setText(_translate('Dialog', '0.5'))
        self.label_4.setText(_translate('Dialog', 'FPFH最大近邻:'))
        self.lineEdit_4.setText(_translate('Dialog', '30'))
        self.label_7.setText(_translate('Dialog', '距离设置:'))
        self.lineEdit_5.setText(_translate('Dialog', '0.05'))
        self.pushButton.setText(_translate('Dialog', '模板路径:'))
        self.pushButton_2.setText(_translate('Dialog', '目标路径:'))
